#!/bin/bash

# Skip manual check
if [ "$1" = 'manualcheck' ]; then
	echo 'Manual check: skipping'
	exit 0
fi

# Munki database check
CWD=$(dirname $0)
CACHEDIR="$CWD/cache/"
MANAGEDINSTALLDIR=$(osascript -l JavaScript -e "ObjC.import('Foundation'); ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('ManagedInstalls').objectForKey('ManagedInstallDir'))")

if [[ -f "${MANAGEDINSTALLDIR}"/application_usage.sqlite ]]; then

/usr/bin/sqlite3 "${MANAGEDINSTALLDIR}"/application_usage.sqlite <<!
.headers off
.mode csv
.output ${CACHEDIR}appusage.csv
SELECT event, bundle_id, app_version, app_path, number_times, last_time FROM application_usage;
!

# crankd check
elif [[ -f /private/var/db/application_usage.sqlite ]]; then

    /usr/bin/sqlite3 /private/var/db/application_usage.sqlite <<!
.headers off
.mode csv
.output ${CACHEDIR}appusage.csv
SELECT event, bundle_id, app_version, app_path, number_times, last_time FROM application_usage;
!

# No database found
else

    echo "Error: App usage database not found!"

fi
